{% set name = "matplotlib-scalebar" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f91adc5e4e67ac920a8fa98a55f904d56e5c2da4d56286748c31ec62146362be

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - matplotlib-base
    - pip
    - python {{ python_min }}
    # 0.8.1 uses setuptools but it is changed to hatchling in the development branch
    - setuptools
  run:
    - matplotlib-base
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - matplotlib_scalebar

about:
  home: https://github.com/ppinard/matplotlib-scalebar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Artist for matplotlib to display a scale bar
  doc_url: https://github.com/ppinard/matplotlib-scalebar
  dev_url: https://github.com/ppinard/matplotlib-scalebar

extra:
  recipe-maintainers:
    - ppinard
    - ericpre
