{% set name = "matplotlib-scalebar" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14887af1093579c5e6afae51a0a1ecc3f715cdbc5c4d7ef59cdeec76ee6bb15d

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - matplotlib-base
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - matplotlib_scalebar

about:
  home: https://github.com/ppinard/matplotlib-scalebar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Artist for matplotlib to display a scale bar
  doc_url: https://github.com/ppinard/matplotlib-scalebar
  dev_url: https://github.com/ppinard/matplotlib-scalebar

extra:
  recipe-maintainers:
    - ppinard
    - ericpre
