{% set name = "matplotlib-scalebar" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cf78834e45bb72b8776bcedb6f5c2f643c510a2a95f6edc0bf5054dcc528df8

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - matplotlib-base
    - pip
    - python
  run:
    - matplotlib-base
    - python

test:
  imports:
    - matplotlib_scalebar

about:
  home: https://github.com/ppinard/matplotlib-scalebar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Artist for matplotlib to display a scale bar
  doc_url: https://github.com/ppinard/matplotlib-scalebar
  dev_url: https://github.com/ppinard/matplotlib-scalebar

extra:
  recipe-maintainers:
    - ppinard
    - ericpre
